alias be="bundle exec"
alias serve="python -m SimpleHTTPServer"
alias retag='ctags -R --exclude=vendor --exclude=public --exclude=.svn --exclude=.git --exclude=log --exclude=tmp *'

source ~/.profile
