#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "${ZDOTDIR:-$HOME}/.aliases"

# Customize to your needs...

source '/usr/local/share/chruby/chruby.sh'
source '/usr/local/share/chruby/auto.sh'

# disable command correction
unsetopt correct
